mbta/orbit

- .github/workflows/ci.yml
- Dockerfile
- js/phoenix.ts
- package-lock.json
- package.json
- tailwind.config.ts
- tsconfig.json
Asana Task: A portion of [Install front-end dev tooling](https://app.asana.com/0/1206604030470713/1207302888667751/f)
~~There's an addition to ci but I won't see if it worked until after the PR is open.~~ It worked
- Tests:
> install typescript, run frontend tests in ci

- eslint.config.mjs
- js/phoenix.ts
- package-lock.json
- package.json
- tailwind.config.ts
- tsconfig.json
Asana Task: Part of [Install front-end dev tooling](https://app.asana.com/0/1200689710863995/1207302888667751/f)
- Tests:
> install eslint

- lib/orbit/contact.ex
- priv/repo/migrations/20240605144358_contacts.exs
- test/orbit/contact_test.exs
Asana Task: [Database schema for operator information](https://app.asana.com/0/1206105669438487/1207392640943329/f)
Checklist
- Tests:
> feat: Contact table

- package-lock.json
- package.json
Asana Task: [Title](link)
See mbta/glides#2514.
Checklist
- Tests:
> chore: install typescript-language-server as a dev dependency

- .storybook/main.ts
- .storybook/preview.ts
- js/components/home.tsx
- package-lock.json
- package.json
- stories/colors.mdx
- tailwind.config.ts
Asana Task: part of prep work for [Badge tap UI](https://app.asana.com/0/1200273269966439/1207259534606012/f)
This just adds some niceties to Storybook now that we'll be using it to actually build things. In particular, I followed [these directions](https://storybook.js.org/recipes/tailwindcss) to add the ability to toggle between light and dark mode (though I'm not sure if we're actually going to have a dark mode for the pilot) and then I based the setup of the color palette on [this answer](https://github.com/storybookjs/storybook/discussions/25483#discussioncomment-8029096).
Checklist
- Tests:
- `( )` Okayed the plan for the feature (e.g. the design files, or the Asana …
> Misc Storybook improvements

- lib/orbit/employee.ex
- priv/repo/migrations/20240610151515_contacts_renames.exs
- test/orbit/employee_test.exs
Asana Task: [🛠 Rename "contacts" table to "employees"](https://app.asana.com/0/1206105669438487/1207529598607176/f)
Sliding this in today. Since I committed the wrong, I wanted to fix it.
Checklist
- Tests:
> fix: rename Contact -> Employee; Employee.email_address -> Employee.email

- js/components/modal.tsx
- js/test/components/modal.test.tsx
- package-lock.json
- package.json
- tailwind.config.ts
Asana Task: initial work on [Badge tap UI](https://app.asana.com/0/1200273269966439/1207259534606012/f)
This is just a very simple modal component, and it probably doesn't work well on mobile yet. I didn't opt to try to put this in Storybook since it's sort of weird to add modals there, but I'm splitting this out into its own component so that I can make a separate component for the contents that will go into Storybook.
Checklist
- Tests:
> feat: basic modal component

- js/components/operatorSignIn/operatorSelection.tsx
- js/test/components/operatorSignIn/operatorSelection.test.tsx
- js/test/util/dom.test.ts
- js/util/dom.ts
- stories/components/operatorSignIn/operatorSelection.stories.tsx
- tailwind.config.ts
Asana Task: part of [Badge tap UI](https://app.asana.com/0/1200273269966439/1207259534606012/f)
This sets up some basic contents for the operator sign in process modal. It doesn't yet put it in an actual modal component, but you can view the contents in Storybook and there are also automated tests. I suspect that we'll be moving a lot of this code around as we go (for instance the NFC-specific components will probably go elsewhere), but this is a starting point to work from.
Checklist
- Tests:
- `(X)` Okayed the plan for the feature (e.g. the design files, or the Asana task)
- `( )` No review …
> Add basic OSI modal contents

- js/components/home.tsx
- js/components/operatorSignIn/operatorSignInModal.tsx
- js/test/components/operatorSignIn/operatorSignInModal.test.tsx
Asana Task: final piece of [Badge tap UI](https://app.asana.com/0/1200273269966439/1207259534606012/f)
This basically just takes the contents form #30 and puts them inside the modal from #29. I have it set up to pop up on the landing page because there isn't really anything else there yet. You can close it but currently there's no way to reopen it - this will all come as the rest of the sign-in flow gets worked out.
Note that, because the Restart UI modal handles focus for us (which is great!) the modal gets a user agent default focus style when it pops up, as seen in the screenshot, which clashes slightly with the grayscale styling IMO. This is a more general thing that will also impact other interactive elements, so I think we can address it later.
Checklist
- Tests:
- …
> feat: basic modal on landing page for OSI

- config/prod.exs
This reverts commit a58c3ffc3e4db90ef5db70fb86ef60547344a348.
Asana Task: [Show operator sign in modal with operator info](https://app.asana.com/0/1206105669438487/1207392635878919/f)
Checklist
- Tests:
> Revert "temporarily set job to every 5 minutes for testing in sandbox"

- js/hooks/useNfc.ts
- js/test/helpers/mockHelpers.ts
- js/test/helpers/promiseWithResolvers.ts
- js/test/hooks/useNfc.test.ts
- js/util/nfc.ts
- package-lock.json
- package.json
Asana Task: **[Badge tap action via NFC API](https://app.asana.com/0/1200273269966439/1207259534606015/f)**
This borrows a lot from the [NFC code in Glides](https://github.com/mbta/glides/blob/097cb9f7ffb9f8d4fccf29272a29c321ca8014a5/assets/src/components/operatorSignIn/nfc.tsx), but puts it in a hook to make it a bit more React-y. One other difference is that the bug with being unable to cancel scans that was an issue at the time the Glides NFC functionality was implemented is no longer an issue on current versions of Chrome.
I have done some manual testing by simply rendering the output of the `useNfc` hook onto the page and confirming that it functions as expected. The `useNfc` hook only scans a card once each time it's mounted and then cancels the scan, and unmounting the hook takes …
> feat: useNfc hook

- js/api.ts
- js/browser.ts
- js/test/api.test.ts
- package-lock.json
- package.json
Asana Task: arbitrarily started as part of [Badge tap action via NFC API](https://app.asana.com/0/1200273269966439/1207259534606015/f)
@mathcolo sorry if any of this overlaps with your work on the [other part of the operator sign-in flow that will also have to get data from the backend](https://app.asana.com/0/1200273269966439/1207373383816236/f). I didn't go too far with my work so that if there's duplication we can sync up and take care of resolving it without too much effort.
Also one quick note that this is currently based off of the `lem-nfc-basics` branch because of some test utilities. Once #35 is merged I'll rebase this onto `main`.
Checklist
- Tests:
- `( )` Okayed …
> Front-end basics for making API calls

- lib/orbit/badge_serial.ex
- lib/orbit/employee.ex
- priv/repo/migrations/20240705175329_add_badge_serials.exs
- test/orbit/employee_test.exs
- test/support/factory.ex
Asana Task: [Badge tap action via NFC API](https://app.asana.com/0/1200273269966439/1207259534606015/f)
I realized this didn't necessarily need to wait for the other ticket that's focused on the import, so I did it as part of this task (and removed the corresponding acceptance criterion from the import ticket).
This makes heavy use of the associations feature in Ecto so that once can get / update employee and modify the `badge_serials` value on the `Employee` struct and have the result reflected correctly in the database. It's similar to (albeit simpler than) the RouteTab functionality in Skate.
One addition thing to note is that I took the opportunity to have the migration update the `on_delete` functionality for the associations on the `operator_sign_ins` table, so that we don't have …
> RFID Serial Schema

- js/test/components/operatorSignIn/operatorSignInModal.test.tsx
> fix: mock and assert console.error in operatorSignInModal failure test

- js/components/operatorSignIn/complete.tsx
- js/components/operatorSignIn/operatorSelection.tsx
- js/components/operatorSignIn/operatorSignInModal.tsx
- js/test/components/operatorSignIn/operatorSelection.test.tsx
- js/test/components/operatorSignIn/operatorSignInModal.test.tsx
Asana Task: [Badge tap action via NFC API](https://app.asana.com/0/1200273269966439/1207259534606015/f)
This should be the last major chunk of work on this ticket!
Checklist
- Tests:
- `(X)` Okayed the plan for the feature (e.g. the design files, or the Asana task)
> Surface NFC errors

- js/hooks/useEmployees.ts
- js/test/hooks/useEmployees.test.ts
- lib/orbit_web/controllers/employees_controller.ex
- test/orbit_web/controllers/employees_controller_test.exs
- test/support/factory.ex
Asana Task: [🛠 Finish hooking up preferred first name in Orbit](https://app.asana.com/0/1200882337457260/1207857452276225/f)
A prior PR left preferred first name being overwritten as `undefined`. This finishes it!
Checklist
- Tests:
> feat: finish hooking up preferred name to the UI

- js/components/operatorSignIn/text.tsx
Asana Task: https://app.asana.com/0/1200882337457260/1207881358362308/f
🤦 
Checklist
- Tests:
> fix: update sign-in text

- lib/orbit/authentication/user.ex
- lib/orbit/authentication/user_permission.ex
- priv/repo/migrations/20240724173817_add_user_permissions_column.exs
- test/orbit/authentication/user_permission_test.exs
- test/orbit/authentication/user_test.exs
- test/support/factory.ex
Asana Task: [Set up user access / permissions](https://app.asana.com/0/1200273269966439/1207259534605993/f)
This is just the super basic database-level means of storing user permissions. I have tentatively added operator sign in as the first permission, figuring that we'll definitely need a permission for that. New permissions can be added in subsequent migrations via `ALTER TYPE` statements, though note that with enums in Postgres you can't remove enum values once they've been added.
As far as helped functions and CRUD operations, if I add those it will be in a followup PR, but the out-of-the-box Ecto schema stuff already makes it easy to fetch and update these values, so I'm divided. I think where it will make sense is once we're dealing with additional permissions from Keycloak, in …
> Basic user permissions

- renovate.json
@skyqrose Is there more than this?
Checklist
- Tests:
> feat: add Renovate configuration

- config/runtime.exs
- config/test.exs
- js/api.ts
- js/app.tsx
- js/components/app.tsx
- js/components/operatorSignIn/complete.tsx
- js/components/operatorSignIn/operatorSignInModal.tsx
- js/hooks/useNfc.ts
- js/sentry.ts
- js/test/components/app.test.tsx
- js/util/metadata.ts
- lib/orbit_web/components/layouts/root.html.heex
- lib/orbit_web/controllers/react_app_controller.ex
- lib/orbit_web/router.ex
- package-lock.json
- package.json
- test/orbit_web/controllers/react_app_controller_test.exs
- test/support/helpers.ex
Asana Task: [📐 Orbit install Sentry on frontend](https://app.asana.com/0/1206105669438487/1207620537833336/f)
- Add Sentry
- Add error boundary
- Capture exceptions across the board
Checklist
- Tests:
- `(x)` Has tests **(Has one for metadata. It's otherwise mostly configuration and CSS, so not seeing a huge additional need.)**
> Frontend Sentry

- lib/orbit_web/controllers/admin/admin_controller.ex
- lib/orbit_web/controllers/admin/employee.html.heex
- lib/orbit_web/controllers/admin/rfid.html.heex
- lib/orbit_web/router.ex
- test/orbit_web/controllers/admin_controller_test.exs
Asana Task: [📐 Orbit: allow manually associating a badge serial with an operator for testing](https://app.asana.com/0/1200689710863995/1207890347662644/f)
- Tests:
> delete data at /admin/employee and /admin/rfid

- js/components/home.tsx
- js/components/modal.tsx
- js/components/operatorSignIn/attestation.tsx
- js/components/operatorSignIn/complete.tsx
- js/components/operatorSignIn/list.tsx
- js/components/operatorSignIn/operatorSelection.tsx
- js/components/operatorSignIn/text.tsx
- js/test/components/operatorSignIn/list.test.tsx
Asana Task: [🛠 Orbit Polish](https://app.asana.com/0/1206105669438487/1208045647859196/f)
Some more styling to help with mobile.
**Table display:**
This introduces a soft hyphen around @ signs, if present, so a full email address breaks there. I tried a lot of other solutions, including:
- Splitting `@` parts into different elements; works, but it's complex/annoying
- Zero width space: annoying, because it can land on the pasteboard if copied
- This solution, but setting `hyphenate-character` to '' via inline CSS; bundler removed this I think?
Checklist
- Tests:
- `( )` Reviewed the feature as …
> fix: fixes for mobile rendering

- js/components/operatorSignIn/attestation.tsx
Asana Task: [🛠 Install Fullstory](https://app.asana.com/0/1206105669438487/1207316362183269/f)
Missed a spot in https://github.com/mbta/orbit/pull/131.
Checklist
- Tests:
> fix: Missed one desired fs-mask

- lib/orbit/s3.ex
Asana Task: [🐞 S3.ex anonymous_url/2 will eventually break](https://app.asana.com/0/616151179860796/1207721363846626/f)
Orbit equivalent to https://github.com/mbta/glides/pull/2738.
Checklist
- Tests:
> feat: use BUCKET.s3.amazonaws.com instead of s3.amazonaws.com/BUCKET

- lib/orbit/operator_sign_in.ex
- lib/orbit_web/controllers/sign_in_export_controller.ex
- priv/repo/migrations/20241023111912_alter_operator_sign_ins_radio.exs
- test/orbit_web/controllers/sign_in_export_controller_test.exs
- test/support/factory.ex
Asana Task: [📐 Orbit radio export implementation](https://app.asana.com/0/1206105669438487/1208470646928351/f)
- Add `radio_number` column to database
- CSV: Add `Radio`
- CSV: Reorder
Checklist
- Tests:
> feat: Radio backend + reorder CSV

- config/config.exs
- config/dev.secret.example.exs
- config/prod.exs
- config/runtime.exs
- config/test.exs
- js/components/app.tsx
- js/components/appcues.tsx
- js/util/metadata.ts
- lib/orbit_web/components/layouts/root.html.heex
- lib/orbit_web/controllers/react_app_controller.ex
- lib/orbit_web/router.ex
- test/orbit_web/controllers/react_app_controller_test.exs
Asana Task: [Install Appcues](https://app.asana.com/0/1200273269966439/1207481990454358/f)
Checklist
- Tests:
> feat: Install Appcues

- lib/orbit_web/router.ex
Slack: https://mbta.slack.com/archives/G8Y8HEY2D/p1734984401171269
Deploying to sandbox to try it there.
- Tests:
> fix: allow appcues through the content-security-policy

- lib/orbit_web/router.ex
Asana Task: None, noticed while working on [Orbit auto-refresh](https://app.asana.com/0/1200689710863995/1208671637680878/f)
**Before**:
and the React Developer Tools extension didn't work.
**After**:
The cookie warning is still there, but the others are gone, and react developer tools works.
It is relaxing security a bit to allow `script-src-elem 'unsafe-inline'` but unfortunately I couldn't find a more specific way to allow the extension to work. And this extension is super useful to me, so I think it's worth the security-convenience tradeoff.
React Developer Tools still gave another warning about not being able to find its source maps. I couldn't find how to allow that in the CSP, and seeing the extension's source maps isn't important, so if you use this extension then I recommend …
> fix csp warning, typo and allow react developer tools

- lib/orbit/application.ex
- lib/orbit/telemetry.ex
- test/orbit/telemetry_test.exs
Asana Task: [🛠 Orbit set up telemetry/Oban splunk logging](https://app.asana.com/0/1206105669438487/1207721363846631/f)
This is lifted verbatim from Glides.
📓 NOTE: I left socket telemetry in. Even though we don't have our own websocket connection in Orbit, it's still nice to see the live reload socket getting connections in the local console.
Checklist
- Tests:
> feat: set up telemetry

- js/components/app.tsx
- js/components/ladderPage/ladder.tsx
- js/paths.ts
- js/test/components/ladderPage/ladder.test.tsx
- lib/orbit_web/router.ex
Asana Task: [Set up a new page for the new Orbit ladder](https://app.asana.com/0/1200273269966439/1209646113903410/f)
adding a new barebones page at `/ladder`
Checklist
- Tests:
- `()` Doesn't need tests
> feat: add /ladder

- js/components/ladderPage/ladder.tsx
- js/dateTime.ts
- js/hooks/useVehiclePositions.ts
- js/models/common.ts
- js/models/latlng.ts
- js/models/vehicle_position.ts
- js/test/components/ladderPage/ladder.test.tsx
- js/test/hooks/useVehiclePositions.test.ts
- js/test/models/vehicle_position.test.ts
- lib/orbit_web/auth/auth.ex
- lib/orbit_web/channels/train_locations_channel.ex
- lib/orbit_web/channels/user_socket.ex
- lib/realtime/data/vehicle_position.ex
- lib/realtime/polling_server.ex
- test/orbit_web/channels/train_locations_channel_test.exs
- test/realtime/polling_server_test.exs
Asana Task: [Set up the Elixir/Phoenix socket](https://app.asana.com/1/15492006741476/project/1206105669438487/task/1209646113903408)
Live updating! Just JSON-stringified for now, though.
Checklist
- Tests:
> feat: Set up the websocket for vehicle positions + frontend models

- js/components/ladderPage/ladder.tsx
- js/hooks/useVehiclePositions.ts
- js/models/vehiclePosition.ts
- js/test/helpers/factory.ts
- js/test/hooks/useVehiclePositions.test.ts
- js/test/models/vehiclePosition.test.ts
- lib/orbit_web/channels/train_locations_channel.ex
- test/orbit_web/channels/train_locations_channel_test.exs
Asana Task: [Hook up useVehiclePositions to VehiclePosition model](https://app.asana.com/0/1200273269966439/1210103496602886)
- Change parser function to accept VehiclePositions themselves, not a big string of all the data
- Add a vehiclePositionFactory, which should come in handy in the next couple of weeks
- Remove the big chunk from the bottom of the ladder page, instead going with a tiny little status bar so we can keep an eye on the `useSocket` return value.
Checklist
- Tests:
> feat: Hook up useVehiclePositions to VehiclePosition model

- js/components/app.tsx
- js/components/appcues.tsx
- js/components/header.tsx
- js/components/menus.tsx
- js/test/components/home.test.tsx
- js/test/components/menus.test.tsx
- js/test/components/operatorSignIn/list.test.tsx
- js/test/setupTest.ts
- package-lock.json
- package.json
Renovate's https://github.com/mbta/orbit/pull/183 had issues I had to resolve manually.
- TextDecoder isn't in jsdom, and has to be imported manually
- Followed React Router v7's [update guide](https://reactrouter.com/upgrading/v6)
Checklist
- Tests:
> chore: update to React Router v7

- js/components/ladderPage/ladder.tsx
- js/components/ladderPage/train.tsx
- js/test/components/ladderPage/train.test.tsx
Asana Task: [Attach pill to ladder](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1209815377576595?focus=true)
demo trains include a pulsing Braintree train on main ladder, non-pulsing Ashmont train on Ashmont ladder
Checklist
- Tests:
> feat: Jcc attach pill to ladder

- priv/static/robots.txt
Relevant slack [thread](https://mbta.slack.com/archives/G01E809HUF2/p1748528790162219).
To quote the above thread:
Sentry is sneakily setting up automatic uptime monitors when it detects a URL in a Sentry alert. We're asking all teams to follow [Option 2 in Sentry's documentation](https://docs.sentry.io/product/alerts/uptime-monitoring/automatic-detection/#disabling-automatic-detection) for disabling this feature. Sentry uptime monitoring is a paid feature that TID doesn't want or need, as this is already handled very capably by UptimeRobot.
`*` and `/` select the same set of paths (all possible paths)
Checklist
- Tests:
- `( )` Okayed the plan for the …
> fix: disallow bots

- js/components/ladderPage/ladder.tsx
Asana Task: [Remove padding left of Alewife-Andrew ladder](https://app.asana.com/1/15492006741476/project/1200882337457260/task/1210454158108072)
https://github.com/user-attachments/assets/30b849d5-4222-4a4a-9dfc-19ff33fd4849
Checklist
- Tests:
> fix(ladder): reduce padding overall + remove it on small screen

- js/components/app.tsx
- js/components/ladderPage/train.tsx
- js/components/requireGroup.tsx
- js/groups.ts
- js/test/components/requireGroup.test.tsx
- js/test/groups.test.ts
- lib/orbit_web/auth/groups.ex
Asana Task: Prep for [Sidebar: estimated arrival](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210390452284240) and [Sidebar: Current trip section (data from OCS only)](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210172293290205)
In adding a Orbit TID Staff group, I refactored groups just a little bit to support expecting one of many groups, not just one. So it's like a role system...lite!
Checklist
- Tests:
> refactor: lightly revamp groups and add ORBIT_TID_STAFF

- js/components/ladderPage/ladder.tsx
- js/components/ladderPage/ladderPage.tsx
- js/test/components/ladderPage/ladder.test.tsx
Asana Task: [Create sidebar](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210172293290202?focus=true)
Checklist
- Tests:
> feat: highlight train when sidebar is open

- js/components/ladderPage/sidebar.tsx
- js/test/components/ladderPage/sidebar.test.tsx
Asana Task: [Sidebar: Current trip section (data from OCS only)](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210172293290205)
Checklist
- Tests:
> feat: add Current Trip sidebar section with data placeholders

- lib/orbit_web/components/layouts/app.html.heex
- lib/orbit_web/controllers/ocs/ocs_controller.ex
- lib/orbit_web/controllers/ocs/ocs_html.ex
- lib/orbit_web/controllers/ocs/trains.html.heex
- lib/orbit_web/controllers/ocs/trips.html.heex
- lib/orbit_web/router.ex
- test/orbit_web/controllers/ocs_controller_test.exs
- test/support/factory.ex
Asana Task: [OCS Data: Debug page](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210733384962700)
This should help with keeping an eye on OCS ingestion.
Checklist
- Tests:
> feat: add /ocs/trains and /ocs/trips debugging pages

- js/components/ladderPage/sidebar.tsx
- js/data/stations.ts
- js/test/components/ladderPage/sidebar.test.tsx
- js/test/helpers/factory.ts
- js/util/string.ts
Noticed that `originStation` and `destinationStation` from within the `Vehicle.OCSTrip` was coming over as the all-caps station name (example: `"ALEWIFE"`), not the station id.  Thus, processing them through `getNameForId()` was always resulting in rendering the placeholder `---`.
~~This is a draft because there are some station names coming in that require some extra processing in order to adhere to the designs:~~
- `"JFK/ UMASS BRT"`
- `"JFK/ UMASS ASH"`
- `"CADDIGAN YARD"`
- more tbd...
bare-bones special formatting of JFK & Kendall plus names with multiple parts separated by space in-place to keep things narrowly focused on MVP target audience and usecase
Checklist
- Tests:
- …
> fix: origin & destination station processing in sidebar

- lib/realtime/trip_matcher.ex
- test/realtime/trip_matcher_test.exs
Asana Task: [Tracking & logging: Splunk for OCS trip matching](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210572330010017)
Change from logging counts to logging vehicle IDs to make debugging easier.
Checklist
- Tests:
> feat: log vehicle IDs in missing data statistics

- lib/orbit/authentication/user.ex
- lib/orbit/badge_serial.ex
- lib/orbit/certification.ex
- lib/orbit/employee.ex
- lib/orbit/ocs/repo/train.ex
- lib/orbit/ocs/repo/trip.ex
- lib/orbit/ocs/stream/kinesis_stream_state.ex
- lib/orbit/operator_sign_in.ex
- lib/realtime/data/vehicle_event.ex
- lib/realtime/data/vehicle_position.ex
- priv/repo/migrations/20250728145025_utc_timestamps.exs
Asana Task: 🛠 [Investigate Ecto timestamp timezones](https://app.asana.com/1/15492006741476/project/1200882337457260/task/1210835734470501?focus=true)
I know the ticket just said to investigate, but I ended up writing a migration as part of testing this out.
I can post a more detailed writeup, but in short:
- Ecto defaults to `:naive_datetime` for `timestamps()`, which stores no timezone info and is cast to `NaiveDatetime`. However, the values written to the table do happen to match expected time in UTC.
- This PR updates schemas to use `:utc_datetime`, which is identical in the table, but more explicit w.r.t. intentions, and makes Ecto cast to fully specified `DateTime`.
- For correctness, I included an alter for all existing tables. It is somewhat nominal, since there is no actual …
> fix: use utc for inserted_at/updated_at in all schemas

- README.md
Asana Task: N/A
Ran through local setup of Orbit and this was the only additional change I needed to make while following the README instructions.
Checklist
- Tests:
> docs: add note about needing postgres user

- js/components/ladderPage/train.tsx
Asana Task: [Let HR stakeholders see Orbit sidebar](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210950955796270)
Dave asked for us to change this.
Checklist
- Tests:
> chore: add ORBIT_HR_STAKEHOLDERS to ladder sidebar
