eslint.config.mjs
jest.config.ts
js/helloWorld.test.ts
js/helloWorld.ts
js/test/setupTest.ts
package-lock.json
package.json
tsconfig.json

Asana Task: [Install front-end dev tooling](https://app.asana.com/0/1200689710863995/1207302888667751/f)
I included some modules for testing react code. We don't need it yet, but are likely to, and tracking them down one by one as we run into them would be annoying.
~~I'm evaluating https://www.npmjs.com/package/eslint-plugin-jest , but I'll do that in a separate PR.~~ Edit: It was quick so I added it to this PR.
- Tests:

test: install and setup jest

---

.github/workflows/ci.yml
Dockerfile
README.md
config/dev.exs
config/runtime.exs
docker-compose.yml

Slack context: https://mbta.slack.com/archives/C06Q8TA1PPV/p1717170172999399
@skyqrose @lemald Is this incompatible with config elsewhere (ECS, load balancer, etc.)? I can change only `dev.exs` if we're concerned.
Checklist
- Tests:

Switch port to 4001

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-sandbox.yml
.github/workflows/deploy-staging.yml
.github/workflows/deploy.yml

So this is ready for whenever infrastructure exists.
I don't have a way to test it yet.
Major differences from Glides deploy scripts:
- I've removed any reference to sentry (and a couple other things), since it doesn't exist yet.
- version-name is required in all envs. `version_id` is now a descriptive name that we can use for many purposes, including docker tags and sentry releases. It'll look like `2024-03-07:abc123` or `pr:1:abc123` or `main:abc123`, including the git hash.

deploy workflows

---

.github/workflows/deploy-staging.yml

Bad merge conflict between deploy workflow which had a formatting/syntax error, and the commit that added the formatting check to CI now makes CI fail on main.
This does not check that the deploy workflow actually works, it just unbreaks CI.
If nobody's gonna do anything with Orbit soon, it'd be okay to wait to merge this until we actually get a chance to test deploys later this week.
If somebody does need CI to pass, then we can merge this PR.
- Tests:

ci: format deploy workflow

---

.github/workflows/ci.yml
config/.credo.exs

`credo`s line in our `test_all` task doesn't have `--strict`, but the CI action does. Let's remove what's in the CI action and rely on `.credo.exs` for strict=true.
Checklist
- Tests:

fix: standardize on credo strict

---

.sobelow-conf
lib/orbit_web/router.ex

Asana Task: no PR, just ad-hoc.
I realized that we didn't actually have Sobelow set up such that warnings resulted in CI failures, and we had accumulated some warnings. For the directory traversal thing I think it's best to just turn that one off, but for the secure headers thing I refactored `router.ex` a bit so that the `:accepts_html` plug just calls the `:browser` plug directly to make it clearer that the former is only used when the latter is as well.
Checklist
- Tests:

fix: fix Sobelow errors and make it actually fail CI

---

js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/operatorSelection.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/components/operatorSignIn/text.tsx
js/hooks/useEmployees.ts
js/models/employee.ts
js/test/components/operatorSignIn/attestation.test.tsx
js/test/components/operatorSignIn/operatorSelection.test.tsx
js/test/components/operatorSignIn/operatorSignInModal.test.tsx
js/test/helpers/factory.ts
js/test/hooks/useEmployees.test.ts
lib/orbit_web/controllers/employees_controller.ex
lib/orbit_web/router.ex
package-lock.json
package.json
stories/components/operatorSignIn/attestation.stories.tsx
test/orbit_web/controllers/employees_controller_test.exs

Asana Task: [Show operator sign in modal with operator info](https://app.asana.com/0/1206105669438487/1207373383816236/f)
Add operator sign-in attestation with http fetch to `/api/employees` for name.
⚠️ @lemald This has some boilerplate/todo/comments for preferred first name, even though we haven't integrated it yet.
Checklist
- Tests:

feat: Show operator sign in modal with operator info

---

eslint.config.mjs

Asana Task: none
I noticed that we had been getting the following warning when running ESLint:
```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
```
It's a bit weird because we're on the new configuration format and most of the README for the React ESLint plugin still references the old configuration format, but I finally found the right configuration change to specify `detect` as the version and have the plugin auto-detect while not give us a warning.
Checklist
- Tests:
- `( )` Reviewed the feature …

fix: have eslint react plugin detect react version

---

js/components/operatorSignIn/operatorSelection.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/components/operatorSignIn/types.ts
js/test/components/operatorSignIn/operatorSelection.test.tsx

Asana Task: Follow up on [Fit for Duty Check modal interaction](https://app.asana.com/0/1206105669438487/1207259534606018/f)
Title says it all. Merging two earlier PRs meant sign-ins were hardcoded to method "manual"- nfc signins should get "nfc".
Checklist
- Tests:

fix: nfc signins get 'nfc' method

---

lib/orbit_web/controllers/employees_controller.ex
test/orbit_web/controllers/employees_controller_test.exs

Asana Task: [🐞 orbit: some operators not being returned in API results](https://app.asana.com/0/1200273269966439/1207834935765422/f)
I'm not sure if this fixes all of the exact issues, but it's definitely a case that would cause this problem.
I took inspiration from the second example under [here](https://hexdocs.pm/ecto/Ecto.Query.html#join/5-keywords-examples), the one querying on `Post` and joining to `comments`, since that was a similar case to our own.
Checklist
- Tests:

fix: operators without rfid serials weren't included in API results

---

lib/orbit/import/personnel.ex
test/orbit/import/personnel_test.exs

Asana Task: [🐞 orbit should treat preferred="" as nil](https://app.asana.com/0/1206105669438487/1207881358362318/f)
This is causing empty preferred names to go in as `""`, which are coming into the UI.
Checklist
- Tests:
- `(x)` No review needed (**it's a minor regression**)

fix: preferred name empty string to nil

---

js/models/employee.ts
js/test/hooks/useEmployees.test.ts

Asana Task: [🐞 orbit should treat preferred="" as nil](https://app.asana.com/0/1206105669438487/1207881358362318/f)
oops!
Checklist
- Tests:

fix: preferred_first optional() to nullable()

---

js/browser.ts
js/components/operatorSignIn/list.tsx
js/test/components/operatorSignIn/list.test.tsx

I regret using browser navigation for the back button, because it doesn't work with a direct link to `/list`.
Checklist
- Tests:

fix: change /list's back button to avoid using history.go

---

lib/orbit/authentication/user.ex
lib/orbit_web/auth/auth.ex
lib/orbit_web/auth/guardian.ex
lib/orbit_web/controllers/auth_controller.ex
test/orbit_web/auth/guardian_test.exs
test/orbit_web/controllers/auth_controller_test.exs

Asana Task: [Set up user access / permissions](https://app.asana.com/0/1200273269966439/1207259534605993/f)
This shuffles things around so that the "resource" in Guardian terms is an actual `%User{...}` struct, and adds a non-persisted field that gets set based on the presence or absence of the appropriate group.
Also note that this will trigger an internal server error for users already logged in who don't have a `"groups"` key in their token. Since we don't have real active users yet I don't think it's very important to make it backwards compatible, and you can just clear your cookies for the appropriate domains.
Checklist
- Tests:
- `( )` Okayed the plan for the feature …

Admin permission

---

test/orbit_web/controllers/auth_controller_test.exs
test/test_helper.exs

Asana Task: [🛠 Mute noisy logging during orbit tests](https://app.asana.com/0/1200882337457260/1208126001173865/f), which came out of [📐 Orbit: allow manually associating a badge serial with an operator for testing](https://app.asana.com/0/1200689710863995/1207890347662644/f)
This approach, which was suggested in https://github.com/navinpeiris/logster/issues/29#issuecomment-2306116754 , is even better than what I was expecting. It mutes all logs in passing tests, and collects any logs for failing tests together. Example:
Description goes here.
Include screenshots if relevant.
Checklist
- Tests:
- `( )` Okayed the plan for the feature (e.g. the design files, or the Asana …

test: mute logs for passing tests

---

eslint.config.mjs

I ran into a lint warning that didn't cause eslint to return an error code, which means it would have been able to sneak past CI. Turns out eslint warnings are intended for things that you don't have to fix immediately, like if you're gradually linting a legacy codebase. Everything here should be errors.
- Tests:

test: eslint should error instead of warn

---

js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/hooks/useEmployees.ts
js/models/employee.ts
js/test/components/operatorSignIn/list.test.tsx
js/test/components/operatorSignIn/operatorSignInModal.test.tsx
js/test/helpers/factory.ts
js/test/hooks/useEmployees.test.ts
lib/orbit_web/controllers/employees_controller.ex
test/orbit_web/controllers/employees_controller_test.exs

Asana Task: None. Noticed while doing #104
Stacked on top of #104.
Things this changes:
- first and last name can be nil on the backend, but the frontend assumed they'd always be there. This PR makes them nullable and handles if they're missing.
- The non-preferred first name isn't used on the frontend, so might as well not send it at all, for better privacy and so the frontend doesn't have to juggle the two of them.
- Except for the one spot we accidentally did use first_name instead of preferred_first. Now it'll use the preferred name if available.
- DRYs one place where `lookupDisplayName` was reimplemented.
- Tests:
- `( )` Okayed the plan for the feature (e.g. the …

refactor: frontend employee name fields

---

js/api.ts
js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/operatorSelection.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/hooks/useEmployees.ts
js/models/employee.ts
js/test/api.test.ts
js/test/components/operatorSignIn/list.test.tsx
js/test/components/operatorSignIn/operatorSelection.test.tsx
js/test/components/operatorSignIn/operatorSignInModal.test.tsx
js/test/helpers/factory.ts
js/test/hooks/useEmployees.test.ts
lib/orbit_web/controllers/employees_controller.ex
lib/orbit_web/controllers/rfid_controller.ex
lib/orbit_web/router.ex
test/orbit_web/controllers/employees_controller_test.exs
test/orbit_web/controllers/rfid_controller_test.exs
test/support/factory.ex

Asana Task: Noticed during [📐 Orbit: allow manually associating a badge serial with an operator for testing](https://app.asana.com/0/1200689710863995/1207890347662644/f), discussed in slack.
Instead of sending all badge_serials to the frontend with the employee data, this PR makes a new api endpoint to look them up one by one during sign in.
I'll need help testing this on sandbox (but I see sandbox is in use right now).
- Tests:

refactor: look up badge number by rfid per request

---

js/components/home.tsx
lib/orbit/employee.ex
lib/orbit/import/personnel.ex
lib/orbit_web/controllers/sign_in_export_controller.ex
lib/orbit_web/router.ex
priv/repo/migrations/20240829201608_add_employees_email_index.exs
test/orbit/employee_test.exs
test/orbit/import/personnel_test.exs
test/orbit_web/controllers/sign_in_export_controller_test.exs

Asana Task: [📐 Operator Compliance Export for tap and type](https://app.asana.com/0/1200273269966439/1206604036091421/f)
I think there's a conversation to be had about how to best associate employees and users long-term, but for now I've opted to join them by email, since both tables have email on them and I've made sure that both have indexes on the email column. One thing to note for the future is that we _do not_ yet have a unique index on email in the employees table, but maybe we should?
One other thing I was considering is that there's at least some conceptual overlap between this and the `index` method on the `SignInController`, but the similarity in terms of code is actually only a couple / few lines of Ecto Query, so I'm not sure it's worth trying to unify those into one …

Sign-in record export

---

js/components/operatorSignIn/operatorSignInModal.tsx
js/test/components/operatorSignIn/operatorSignInModal.test.tsx

Asana Task: [🛠 Orbit sign in flow for multiple people in series](https://app.asana.com/0/1200273269966439/1208045647859192/f)
As expected, all that ended up being necessary here was moving some React state around so that it's in a component that's conditionally rendered when the modal is open, and therefore gets reset if the modal is closed and reopened.
Checklist
- Tests:
- `(X)` Okayed the plan for the feature (e.g. the design files, or the Asana task)

fix: move modal interaction state so it's conditionally rendered

---

config/config.exs
config/test.exs
lib/orbit/badge_serial.ex
lib/orbit/import/rfid.ex
lib/orbit_web/controllers/admin/admin_controller.ex
priv/repo/migrations/20240830184718_badge_serial_unique_index.exs
test/orbit/import/rfid_test.exs
test/orbit_web/controllers/admin_controller_test.exs
test/support/helpers.ex

Asana Task: [📐 Orbit: allow manually associating a badge serial with an operator for testing](https://app.asana.com/0/1200689710863995/1207890347662644/f)
Migration to make badge serials unique, and updates to the two ways to create badge serials (/admin/rfid and the csv import) to enforce that.
- Tests:

unique badge serials

---

js/components/operatorSignIn/list.tsx
js/components/operatorSignIn/operatorSelection.tsx

Asana Task: [🛠 Install Fullstory](https://app.asana.com/0/1200273269966439/1207316362183269/f)
To finish off FullStory installation, I'm masking more operator names and badge numbers from capture.
Checklist
- Tests:

feat: Mask more data display from FullStory

---

lib/orbit_web/controllers/sign_in_controller.ex
test/orbit_web/controllers/sign_in_controller_test.exs

Asana Task: [🐞 Orbit Ecto.NoResultsError on invalid badge entry](https://app.asana.com/0/1200882337457260/1208298977479188/f)
Sentry noise from this is untenable, so let's just not raise.
Checklist
- Tests:

fix: don't raise on invalid employee during signin

---

js/api.ts
js/components/operatorSignIn/list.tsx

Asana Task: [🐞 Orbit react error after Chrome quit on Android](https://app.asana.com/0/1206105669438487/1208214593975946/f)
The errors coming from `useSignins` via `useApiResult` are Objects, which React won't display as a node (understandably). So I could have string concatenated them with `+` to get them to display regardless, but meh. Let's just `console.error` (which we can retrieve via other means) and display nothing to the end user.
Checklist
- Tests:
- `(x)` Doesn't need tests **This is removing functionality that didn't work in the first place..**
- `( )` Reviewed the feature as implemented (e.g. on dev-green, …

fix: Prevent List component from erroring on displaying errors

---

js/components/operatorSignIn/list.tsx
js/models/signin.ts
js/test/components/operatorSignIn/list.test.tsx
js/test/hooks/useSignins.test.ts
lib/orbit_web/controllers/sign_in_controller.ex
test/orbit_web/controllers/sign_in_controller_test.exs

Asana Task: [📐 Orbit: In-app view of completed sign-ins does not include official full name](https://app.asana.com/0/1206105669438487/1208171871591943/f)
Display officials' names in the list, with email address as fallback.
Checklist
- Tests:

feat: osi list shows officials' name with email as fallback

---

lib/orbit/employee.ex
test/orbit/employee_test.exs
test/orbit_web/controllers/sign_in_controller_test.exs

Asana Task: [🐞 [employee] is weird in Orbit](https://app.asana.com/0/1200882337457260/1208356829197703/f)
See task^'s comments. Changing so email is substituted in if name data from HR/CMS is blank.
Checklist
- Tests:

fix(Employee): Use official's email address if names are blank

---

js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/operatorSelection.tsx
js/test/components/operatorSignIn/attestation.test.tsx
js/test/components/operatorSignIn/operatorSelection.test.tsx
js/util/string.ts

Asana Task: [Allow leading zero in Orbit type workaround](https://app.asana.com/0/1206105669438487/1208362994470250/f)
Ignore leading zero in operator selection & attestation, as we cannot tell what personnel are used to.
Checklist
- Tests:

fix(OperatorSelection): ignore leading zeroes

---

js/components/operatorSignIn/operatorSelection.tsx

In #164 I fixed the Enter/Go key on the Attestation by switching to an HTML `<form>`; doing it here for OperatorSelection too.
Checklist
- Tests:

fix(operatorSelection): fix Enter/Go key with <form>

---

js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/list.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/components/operatorSignIn/text.tsx
js/models/signin.ts
js/test/components/operatorSignIn/attestation.test.tsx
js/test/components/operatorSignIn/list.test.tsx
js/test/components/operatorSignIn/operatorSignInModal.test.tsx
js/test/hooks/useSignins.test.ts
lib/orbit_web/controllers/sign_in_controller.ex
test/orbit_web/controllers/sign_in_controller_test.exs

Asana Task: [📐 Orbit radio UI implementation](https://app.asana.com/0/1206105669438487/1208470630634721/f)
Still need to do some testing on mobile (as of this writing I don't have my phone accessible), but otherwise this is radio added to the frontend list display + form pages in a #163-not-ready-yet compatible way. That PR should be merged first.
Checklist
- Tests:

feat: Radio frontend

---

eslint.config.mjs
js/test/api.test.ts
js/test/helpers/metadata.ts
js/test/helpers/promiseWithResolvers.ts

This has been bugging me for a while, passing tests shouldn't print error messages. I finally spent 15 minutes to fix it.
Before:
After:
- Tests:

chore: quiet console.error in passing api.test.ts

---

tailwind.config.ts

Asana Task: [Update the red color in Glides + Orbit](https://app.asana.com/0/1208918247656304/1208002952543253/f)
Description goes here.
Include screenshots if relevant.
Checklist
- Tests:
Note:
The red-100 color is not used and so this PR removes it.
Before: 
<br>
After:

fix: update red-200. remove unused red-100

---

lib/orbit/certification.ex
lib/orbit/import/certifications.ex
lib/orbit/rail_line.ex
priv/repo/migrations/20250106153058_truncate_certifications.exs
priv/repo/migrations/20250106164510_rail_line_add_unknown.exs
test/orbit/import/certifications_test.exs

Asana Task: [📐 Implement Warnings for Expiring Certifications](https://app.asana.com/0/1206105669438487/1208729753338210/f)
I made the assumption in my earlier Orbit changes to import certifications that Postgres treats nulls as a singleton, i.e. they violate unique constraints and would trigger an upsert. But that isn't available until PostgreSQL 15.x :-( It's possible to do with multiple partial indexes, but with downstream downsides. I think this is better.
⚠️ THIS CONTAINS A MIGRATION THAT TRUNCATES `certifications`.
Checklist
- Tests:
- `( )` Reviewed the feature as implemented (e.g. on …

fix: RailLine enum option :none replaces nil + truncate certifications

---

js/components/operatorSignIn/attestation.tsx
js/components/operatorSignIn/operatorSignInModal.tsx
js/hooks/useCertifications.ts
js/models/certification.ts
js/test/hooks/useCertifications.test.ts
js/test/models/certification.test.ts
js/types.ts

Asana Task: [📐 Implement Warnings for Expiring Certifications](https://app.asana.com/0/1206105669438487/1208729753338210/f)
Mix of a feature and a fix. Filter out certifications for other lines, so that:
1. (feature) we only evaluate BL operators against BL certifications. will make RL and OL easier.
2. (fix) old rail certifications in the data that are lineless (don't match the format) are filtered out.
Checklist
- Tests:

fix(certifications): filter out certifications that aren't relevant for BL signin

---

lib/orbit_web/controllers/sign_in_controller.ex
lib/orbit_web/plugs/require_login.ex

Asana Task: [🛠 Orbit saves user in Sentry metadata](https://app.asana.com/0/1206105669438487/1207620537833332/f)
Include user.email in Sentry metadata so Sentry traces that have passed through the RequireLogin plug will have that attached to it.
Checklist
- Tests:

feat: set Sentry user context in require_login

---

eslint.config.mjs
js/app.tsx
js/socket.ts
js/test/helpers/socket.ts
js/test/hooks/useNfc.test.ts
js/test/setupTest.ts
js/test/socket.test.ts
js/util/metadata.ts
lib/orbit_web/auth/auth.ex
lib/orbit_web/channels/metadata_channel.ex
lib/orbit_web/channels/user_socket.ex
lib/orbit_web/components/layouts/root.html.heex
lib/orbit_web/controllers/react_app_controller.ex
lib/orbit_web/endpoint.ex
test/orbit_web/channels/metadata_channel_test.exs
test/support/channel_case.ex

Asana Task: [📐 Orbit auto-refresh](https://app.asana.com/0/1200689710863995/1208671637680878/f)
Status: I'm not quite done, but I wanted to get what I have pushed, and I'm ready for reviews.
Things I still need to do:
Makes a new socket. The server tells the client if they're unauthenticated and need to refresh to re-login, or out of date and need to refresh to get a new version.
Unfortunately you can't give an error reason when rejecting a socket connection, so it has to accept the connection and then send the reply. And also unfortunately, you can't reply to a socket connection, so the client has to join a channel and get the reply to that channel join. (I made a phoenix feature request to allow replies so we wouldn't need those workarounds: [Elixir Forum: Feature request: Reply to …

connect to socket and reload if out of date or unauthenticated

---

lib/orbit_web/router.ex

Fixes this problem:
This problem was introduced in https://github.com/mbta/orbit/pull/218 . I fixed one thing but broke another, cuz the new `script-src-elem` was overriding the `script-src` that was allowing appcues and fullstory.
Deploying to sandbox to test.
- Tests:

fix: appcues and fullstory csp

---

config/config.exs
config/dev.exs
config/runtime.exs
config/test.exs
docker-compose.yml
lib/orbit/application.ex
lib/realtime/polling_server.ex
lib/realtime/rtr.ex
test/realtime/polling_server_test.exs

Asana Task: [Set up the polling GenServer for vehicle positions and trip updates](https://app.asana.com/0/1200273269966439/1209646113903406)
Checklist
- Tests:

feat: jcc set up polling gen server

---

lib/orbit_web/channels/train_locations_channel.ex
test/orbit_web/channels/train_locations_channel_test.exs

Asana Task: [Hook up useVehiclePositions to VehiclePosition model](https://app.asana.com/0/1200273269966439/1210103496602886)
The channel sends vehicle positions in two cases:
a) On channel join
b) On each poll of upstream
[b] was working, while [a] was still sending a JSON-stringified version of the full data. So https://orbit-staging.mbtace.com/ladder displays "Status: Connected", but errors at first. It only works after the next routine poll, making it appear to take 1-3 additional seconds to load.
Checklist
- Tests:
- `( )` Reviewed the feature as implemented (e.g. on dev-green, or saw …

fix: vehicle position channel was sending an invalid object on join

---

js/models/tripUpdate.ts
lib/realtime/data/trip_update.ex

Asana Task: [Crash due to non-nullable TripUpdates fields](https://app.asana.com/1/15492006741476/project/1200882337457260/task/1210526410605224?focus=true)
This is a quick fix for the null direction crash. I haven't fully sifted through the trip updates JSON and the GTFS spec, but it looks like there are cases where `direction_id` is not provided, and the orbit backend ends up mapping that into a value of `direction: nil`. The orbit frontend expects this to be non-null, and so zod crashes during parsing.
Whether these values should be allowed in the long term is a bigger question, but right now we're not using them, so I think it's worth merging this in the short-term.
Checklist
- Tests:
- `(X)` Tests deferred (with justification)
- …

fix(trip_updates): handle null fields in trip_update parsing

---

lib/orbit/ocs/train.ex
lib/orbit/ocs/trip.ex
priv/repo/migrations/20250617182608_ocs.exs
test/orbit/ocs/train_test.exs
test/orbit/ocs/trip_test.exs

Asana Task: [🛠 Set up data structures for OCS trainsheets](https://app.asana.com/1/15492006741476/project/1206105669438487/task/1210389787136611)
Create two new tables to populate with OCS data as we receive it:
1. ocs_trips
2. ocs_trains
NB: I'm not using foreign key constraints here, as I don't have enough certainty about the order of insertion. So I'm expecting using this data to be best-effort.
Checklist
- Tests:

feat(ocs): add ocs_trips and ocs_trains tables

---

lib/orbit/ocs/repo/entities.ex
lib/orbit/ocs/repo/trip.ex
lib/orbit_web/controllers/ocs/trips.html.heex
lib/realtime/trip_matcher.ex
priv/repo/migrations/20250711191108_alter_ocs_trip_assigned_at_column.exs
test/orbit/ocs/repo/entities_test.exs
test/realtime/trip_matcher_test.exs

Asana Task: [Read in the OCS raw messages](https://app.asana.com/1/15492006741476/project/1210239137170761/task/1209929021017070?focus=true)
This change attempts to improve our trip matching logic based on a few assumptions / observations of OCS messages, namely:
1. A `TSCH_ASN` message is a reasonable indicator that a train has been assigned to a "current" trip, as they typically come through shortly before the first `TMOV` of the trip.
- Exception: It appears to be common in the early morning (~6 am) in cases where a train is being assigned to its first trip of the day, for these messages to come in an hour+ ahead of time (say ~4:45am), but I think in that case Orbit would still want to convey that to users.
2. Finding the "next" trips for a train cannot really be done by looking for …

feat(ocs): match trips based on TSCH_ASN and "next" trip UIDs

---

lib/orbit/ocs/parser/parser.ex
lib/orbit/ocs/parser/tsch_message.ex
lib/orbit/ocs/stream/message_handler.ex
lib/orbit/ocs/stream/pipeline.ex
lib/orbit/ocs/utilities/time.ex
test/orbit/ocs/stream/pipeline_test.exs
test/orbit/ocs/utilities/time_test.exs

Continued work on Asana Task: [Read in the OCS raw messages](https://app.asana.com/1/15492006741476/project/1210239137170761/task/1209929021017070?focus=true)
For context: OCS messages contain an `hh:mm:ss` timestamp that indicates when the relevant change occurred in OCS. Since these timestamps are not fully specified, in that they don't tell you the actual _date_, the parser must infer that.
Two changes here:
- The parser would previously infer the relevant date based on _current time_. If we are receiving messages in realtime, this is reasonable, but not if Orbit is processing old messages from Kinesis. It makes more sense to use the timestamp that the CloudEvent was emitted by Trike, since that's a more accurate indicator of when OCS actually emitted this change.
- I've taken a stab …

feat(ocs): revise message timestamp handling

---

lib/orbit/application.ex
lib/orbit/rail_line.ex
lib/realtime/data/stations.ex
lib/realtime/data/vehicle_event.ex
lib/realtime/vehicle_event_detector.ex
lib/util/list.ex
priv/repo/migrations/20250717170938_vehicle_events.exs
test/realtime/vehicle_event_detector_test.exs
test/util/list_test.exs

Asana Task: [Sidebar: actual departure (track departures automatically)](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1209646113903412)
This PR:
- Brings a heavy rail version of VehicleEventDetector over to Orbit
- ⚠️ Does not yet record or facilitate recording `actual_departure` anywhere. That's tomorrow!
Checklist
- Tests:

feat: add VehicleEventDetector

---

lib/realtime/trip_matcher.ex
test/realtime/trip_matcher_test.exs

Asana Task: [Sidebar: actual departure (track departures automatically)](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1209646113903412)
If a vehicle is at its origin, it's probably getting an actual departure from earlier in the day (but within the cutoff). So we shouldn't display one in that case.
Checklist
- Tests:

fix: don't apply actual departure when at origin

---

lib/orbit/ocs/parser/tsch_message.ex
test/orbit/ocs/parser/tsch_message_test.exs

Asana Task: [🪐 OCS Data: Allow message parser to handle additional fields](https://app.asana.com/1/15492006741476/project/1200882337457260/task/1210872848363835?focus=true)
We are preparing to ask OCC to add explicit date fields at the end of certain `TSCH` messages (specifically `TSCH_NEW` and `TSCH_DST`), preferably appended at the end of the existing format, for easier backward compatibility. Unfortunately that would break our current parser, because we expect exact numbers of fields for each message type.
This change allows us to receive and ignore extra fields. (The exception is `TSCH_TAG` because that message does not specify a way to terminate the arbitrary-length list of tags at the end.) I don't know that we'll actually need this, but it will make us more resilient to unexpected …

feat(ocs): ignore extra fields at end of TSCH messages

---

js/components/ladderPage/sidebar.tsx
js/test/components/ladderPage/sidebar.test.tsx

Asana Task: [Sidebar: late notice box](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210172293290211)
Checklist
- Tests:

fix: negatives in late boxes

---

README.md
js/telemetry/trackingEvents.ts
js/test/telemetry/trackingEvents.test.ts

This is a follow-up for Asana Task: [Tracking: fullstory event on sidebar open](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1210572330010013?focus=true)
Custom event tracking for the sidebar relies on Orbit being configured with the FS org ID, which can be set locally in `dev.secret.exs`. If this ID is missing, FS is not initialized, which is fine, except that this causes the side bar event to crash, preventing the side bar from opening.
This adds an explicit check for initialization, and if not, skips the event. 
Checklist
- Tests:
- `( )` Reviewed the feature as …

fix: avoid event tracking crash if FS is not initialized

---

lib/realtime/trip_matcher.ex
test/realtime/trip_matcher_test.exs

Asana Task: [🪐🐞 Orbit: Fix trip matcher "missing" stats in splunk](https://app.asana.com/1/15492006741476/project/1200273269966439/task/1211008266929600?focus=true)
Two changes:
- Log that the actual departure for the current trip is missing only if we are actually missing the departure time. (Previously this was just always reporting as missing for every trip.)
- If the current trip itself is missing, then departure time is also considered missing
- If the current trip is present _and has departed_, then log if the actual departure time is missing.
- For cases where we have a current trip with no next trip UID, then _do not_ log that the missing trip fields are missing, as this is a case where the next trip is considered explicitly unset by OCS.
Checklist
- Tests:
- `( …

fix: revise trip matcher splunk stats for "missing" trip fields
